### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by Ilshidur**
This also fixes a [known vulnerability](https://snyk.io/test/npm/node-rest-client/3.1.0).

Awesome project by the way !

### CODE REVIEW

**Comment by haalcala** [comment]
Can we please merge this?

**Comment by mattrat** [comment]
This commit might need to be updated. The debug package should go up to 3.1.0.

**Comment by Ilshidur** [comment]
Done.

**Comment by ashalliants** [comment]
Please merge this, it will make my security compliance team very happy!

**Comment by rob-pocklington-a139759** [comment]
Is there any reason this hasn't been merged?

**Comment by Ilshidur** [comment]
Because it looks like the owner and unique maintainer [has not been active since March 2017](https://github.com/aacerox?tab=overview&from=2017-12-01&to=2017-12-31) ...

I suggest to just move on and use [Axios](https://github.com/axios/axios) :
[![NPM][npm-stats-badge]][npm-stats-url]

[npm-stats-badge]: https://nodei.co/npm/axios.png?downloads=true&downloadRank=true
[npm-stats-url]: https://nodei.co/npm/axios

**Comment by Ilshidur** [comment]
I give up. Closing this issue and good riddance.

**Pull request closed without merging**
